import numpy as np
N=10
def make_numberbracelet(a,b):
    
    number = (a+b)%N
    bracelet = [a,b]
    next = (bracelet[-2]+bracelet[-1]) %N
    bracelet.append(next)
    while (bracelet[-2]!=a) or (bracelet[-1] !=b):
        next = (bracelet[-2]+bracelet[-1]) %N
        bracelet.append(next)
    bracelet= bracelet[:-2] #removes the last one from the bracelet since the final two elements are the same as the first two
    return bracelet

def same_bracelet(b1, b2):
    if len(b1) != len(b2):
        return False
    n = len(b1)
    for k in range(n):
        match = True
        for i in range(n):
            if b1[(i + k) % n] != b2[i]:
                match = False
                break
        if match:
            return True

    return False

numbracelets =0    #CLAIM 1
braceletlist = []
for i in range(N):
    for j in range(N):
        thisbracelet = make_numberbracelet(i,j)
        new = True
        for bracelet in braceletlist:
            if same_bracelet(thisbracelet,bracelet[0]) == True:
                new = False
        if new ==True:
            braceletlist.append([thisbracelet,i,j])

print('The number of different bracelets is:')
print(len(braceletlist))
print('These are the bracelets generated by the following pairs:')
for i in range(len(braceletlist)):
    print(braceletlist[i][1],braceletlist[i][2])
print('In other words, any bracelet is the same the bracelet generated by one of these 6 pairs')


for bracelet in braceletlist:  #This is for checking that the answer is correct in section 4
    print(bracelet)
    print(len(bracelet[0]))

for i in range(1,51):    #This is for producing table 2
    N=i
    braceletlist =[]
    for k in range(N):
        for j in range(N):
            thisbracelet = make_numberbracelet(k,j)
            new = True
            for bracelet in braceletlist:
                if same_bracelet(thisbracelet,bracelet[0]) == True:
                    new = False
            if new ==True:
                braceletlist.append([thisbracelet,k,j])
    print(f"S({i})={len(braceletlist)}")